from machine import Pin
from  utime import sleep
redled=Pin(1,Pin.OUT)
amberled=Pin(3,Pin.OUT)
greenled=Pin(5,Pin.OUT)
while True:
     redled.value(0)
     amberled.value(0)
     greenled.value(0)
     sleep(2)
     redled.value(0)
     amberled.value(0)
     greenled.value(1)
     sleep(2)
     redled.value(0)
     amberled.value(1)
     greenled.value(0)
     sleep(2)
     redled.value(0)
     amberled.value(1)
     greenled.value(1)
     sleep(2)
     redled.value(1)
     amberled.value(0)
     greenled.value(0)
     sleep(2)
     redled.value(1)
     amberled.value(0)
     greenled.value(1)
     sleep(2)
     redled.value(1)
     amberled.value(1)
     greenled.value(0)
     sleep(2)
     redled.value(1)
     amberled.value(1)
     greenled.value(1)